CREATE DATABASE HotelManagement;

USE HotelManagement;

CREATE TABLE [ROOM] (
	ROOMID int NOT NULL,
	ROOMTYPEID int NOT NULL,
	ROOMNAME nvarchar(255) NOT NULL,
	ROOMDESCRIPTION nchar(255),
	BEDQUANTITY int NOT NULL,
	STATUS int NOT NULL,
	CREATEDDATE datetime,
	CREATEDUSER nvarchar(255),
	ISDELETED int NOT NULL,
	DELETEDUSER nvarchar(255),
	DELETEDDATE datetime,
	UPDATEDDATE datetime,
  CONSTRAINT [PK_ROOM] PRIMARY KEY CLUSTERED
  (
  [ROOMID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [ROOMTYPE] (
	ROOMTYPEID int NOT NULL,
	ROOMTYPENAME nvarchar(255) NOT NULL,
	ROOMTYPEDESCRPTION nvarchar(255),
	PRICEPERHOUR bigint NOT NULL,
	PRICEPERDAY bigint NOT NULL,
	CREATEDUSER nvarchar(255) NOT NULL,
	CREATEDDATE datetime,
	ISDELETED int NOT NULL,
	DELETEDUSER nvarchar(255),
	DELETEDDATE datetime,
	UPDATEDDATE datetime,
  CONSTRAINT [PK_ROOMTYPE] PRIMARY KEY CLUSTERED
  (
  [ROOMTYPEID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [BILL] (
	BILLID int NOT NULL,
	BOOKINGID int NOT NULL,
	BEGINDATE datetime NOT NULL,
	ENDDATE datetime NOT NULL,
	TOTALMONEY bigint NOT NULL,
	CREATEDUSER nvarchar(255),
	CREATEDDATE datetime,
	ISDELETED int NOT NULL,
	DELETEDUSER nvarchar,
	DELETEDATE datetime,
	UPDATEDDATE datetime,
  CONSTRAINT [PK_BILL] PRIMARY KEY CLUSTERED
  (
  [BILLID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [BILLDETAIL] (
	BILLDETAILID int NOT NULL,
	BILLID int NOT NULL,
	PRODUCTSERVICEID int,
	PRICE bigint NOT NULL,
  CONSTRAINT [PK_BILLDETAIL] PRIMARY KEY CLUSTERED
  (
  [BILLDETAILID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [PRODUCT] (
	PRODUCTID int NOT NULL,
	PRODUCTNAME nvarchar(255) NOT NULL,
	PRICE bigint NOT NULL,
	ISDELETED int NOT NULL DEFAULT '0',
  CONSTRAINT [PK_PRODUCT] PRIMARY KEY CLUSTERED
  (
  [PRODUCTID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [PRODUCTSERVICE] (
	PRODUCTSERVICEID int NOT NULL,
	PRODUCTID int NOT NULL,
	QUANTITY int NOT NULL,
  CONSTRAINT [PK_PRODUCTSERVICE] PRIMARY KEY CLUSTERED
  (
  [PRODUCTSERVICEID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [BOOKINGROOM] (
	BOOKINGID int NOT NULL,
	ROOMID int NOT NULL,
	CUSTOMERNAME nvarchar(255) NOT NULL,
	CUSTOMERIDENTIFY nvarchar(255) NOT NULL,
	ISRESERVE bit NOT NULL,
	RESERVATEDATE datetime NOT NULL,
	DEPOSITMONEY bigint NOT NULL,
	CREATEDUSER nvarchar,
	CREATEDDATE datetime,
	ISDELETED int NOT NULL,
	DELETEDUSER nvarchar,
	DELETEDDATE datetime,
	UPDATEDDATE datetime,
  CONSTRAINT [PK_BOOKINGROOM] PRIMARY KEY CLUSTERED
  (
  [BOOKINGID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
CREATE TABLE [USER] (
	USERID int NOT NULL,
	USERNAME varchar(255) NOT NULL,
	PASSWORD varchar(255) NOT NULL,
	EMPLOYEENAME nvarchar(255) NOT NULL,
	DOB datetime NOT NULL,
	SEX nvarchar NOT NULL UNIQUE,
	PHONENUMBER varchar(255) NOT NULL UNIQUE,
	ADDRESS nvarchar NOT NULL UNIQUE,
	EMAIL nvarchar NOT NULL UNIQUE,
	ISADMIN int NOT NULL DEFAULT '0',
	ISDELETED int NOT NULL DEFAULT '0',
  CONSTRAINT [PK_USER] PRIMARY KEY CLUSTERED
  (
  [USERID] ASC
  ) WITH (IGNORE_DUP_KEY = OFF)

)
GO
ALTER TABLE [ROOM] WITH CHECK ADD CONSTRAINT [ROOM_fk0] FOREIGN KEY ([ROOMTYPEID]) REFERENCES [ROOMTYPE]([ROOMTYPEID])
ON UPDATE CASCADE
GO
ALTER TABLE [ROOM] CHECK CONSTRAINT [ROOM_fk0]
GO


ALTER TABLE [BILL] WITH CHECK ADD CONSTRAINT [BILL_fk0] FOREIGN KEY ([BOOKINGID]) REFERENCES [BOOKINGROOM]([BOOKINGID])
ON UPDATE CASCADE
GO
ALTER TABLE [BILL] CHECK CONSTRAINT [BILL_fk0]
GO

ALTER TABLE [BILLDETAIL] WITH CHECK ADD CONSTRAINT [BILLDETAIL_fk0] FOREIGN KEY ([BILLID]) REFERENCES [BILL]([BILLID])
ON UPDATE CASCADE
GO
ALTER TABLE [BILLDETAIL] CHECK CONSTRAINT [BILLDETAIL_fk0]
GO
ALTER TABLE [BILLDETAIL] WITH CHECK ADD CONSTRAINT [BILLDETAIL_fk1] FOREIGN KEY ([PRODUCTSERVICEID]) REFERENCES [PRODUCTSERVICE]([PRODUCTSERVICEID])
ON UPDATE CASCADE
GO
ALTER TABLE [BILLDETAIL] CHECK CONSTRAINT [BILLDETAIL_fk1]
GO


ALTER TABLE [PRODUCTSERVICE] WITH CHECK ADD CONSTRAINT [PRODUCTSERVICE_fk0] FOREIGN KEY ([PRODUCTID]) REFERENCES [PRODUCT]([PRODUCTID])
ON UPDATE CASCADE
GO
ALTER TABLE [PRODUCTSERVICE] CHECK CONSTRAINT [PRODUCTSERVICE_fk0]
GO

ALTER TABLE [BOOKINGROOM] WITH CHECK ADD CONSTRAINT [BOOKINGROOM_fk0] FOREIGN KEY ([ROOMID]) REFERENCES [ROOM]([ROOMID])
ON UPDATE CASCADE
GO
ALTER TABLE [BOOKINGROOM] CHECK CONSTRAINT [BOOKINGROOM_fk0]
GO
