//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLDETAIL
    {
        public int BILLDETAILID { get; set; }
        public int BILLID { get; set; }
        public Nullable<int> PRODUCTSERVICEID { get; set; }
        public long PRICE { get; set; }
    
        public virtual BILL BILL { get; set; }
        public virtual PRODUCTSERVICE PRODUCTSERVICE { get; set; }
    }
}
