//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKINGROOM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOKINGROOM()
        {
            this.BILLs = new HashSet<BILL>();
        }
    
        public int BOOKINGID { get; set; }
        public int ROOMID { get; set; }
        public string CUSTOMERNAME { get; set; }
        public string CUSTOMERIDENTIFY { get; set; }
        public bool ISRESERVE { get; set; }
        public System.DateTime RESERVATEDATE { get; set; }
        public long DEPOSITMONEY { get; set; }
        public string CREATEDUSER { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public int ISDELETED { get; set; }
        public string DELETEDUSER { get; set; }
        public Nullable<System.DateTime> DELETEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BILL> BILLs { get; set; }
        public virtual ROOM ROOM { get; set; }
    }
}
