//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOMTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ROOMTYPE()
        {
            this.ROOMs = new HashSet<ROOM>();
        }
    
        public int ROOMTYPEID { get; set; }
        public string ROOMTYPENAME { get; set; }
        public string ROOMTYPEDESCRPTION { get; set; }
        public long PRICEPERHOUR { get; set; }
        public long PRICEPERDAY { get; set; }
        public string CREATEDUSER { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public int ISDELETED { get; set; }
        public string DELETEDUSER { get; set; }
        public Nullable<System.DateTime> DELETEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ROOM> ROOMs { get; set; }
    }
}
