//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int USERID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string EMPLOYEENAME { get; set; }
        public System.DateTime DOB { get; set; }
        public string SEX { get; set; }
        public string PHONENUMBER { get; set; }
        public string ADDRESS { get; set; }
        public string EMAIL { get; set; }
        public int ISADMIN { get; set; }
        public int ISDELETED { get; set; }
    }
}
